export const styles = {
  monthContainer: {
    display: "flex",
    flexDirection: "column",
    width: "90%",
    m: "0 auto",
  },
  monthTitle: {
    display: "flex",
    justifyContent: "space-between",
  },
  monthTitleElement: {
    fontSize: "2rem",
    color: "color.hover",
  },
  monthContent: {
    border: "1px solid",
    borderColor: "color.other",
  },
  monthWeek: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1fr 1fr 1fr 1fr 1fr",
    justifyContent: "space-between",
    bgcolor: "color.other",
    border: "1px solid",
    borderColor: "color.other",
    color: "text.secondary",
  },
  monthDay: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    maxWidth: "150px",
    height: "35px",
    gap: "10px",
  },
  monthWrapper: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1fr 1fr 1fr 1fr 1fr",
    gridTemplateRows: "1fr 1fr 1fr 1fr 1fr 1fr",
  },
  monthTable: {
    border: "1px solid",
    borderColor: "color.other",
  },
  monthEmptyCell: {
    display: "flex",
    justifyContent: "start",
    alignItems: "start",
    maxWidth: "150px",
    height: "70px",
    gap: "10px",
    p: "5px",
    borderRadius: "0px",
    border: "1px solid",
    borderColor: "color.other",
    lineHeight: "1",
    color: "color.disabled",
  },
};
